# ==========================================
# PURE CTC ASR CONFIGURATION (Raw Audio -> WavLM -> CTC)
# ==========================================

# --- 1. EXPERIMENT INFO ---
experiment:
  project_name : "wavlm-ctc-asr-v1" 
  seed         : 42              
  output_dir   : "./logs/experiments"
  use_wandb    : True

# --- 2. DATA PIPELINE ---
data:
  # Path disesuaikan dengan skrip offline preprocessing kita
  # Ubah ke /content/... jika Anda menjalankannya di Colab
  train_manifest  : "./data/processed/train_phon_transcripts.jsonl"
  val_manifest    : "./data/processed/val_phon_transcripts.jsonl"
  
  # [WAJIB] Path ke kamus 52 karakter kompetisi
  vocab_path      : "./data/processed/vocab.json"
  
  # [WAJIB] Nama kolom transkrip di dalam file JSONL
  target_column   : "phonetic_text"

  noise_dir       : "./data/raw/noise"
  noise_prob      : 0.5
  
  sample_rate     : 16000
  
  # Batch Size diturunkan ke 8 agar aman dari OOM
  batch_size      : 8
  num_workers     : 4 
  min_duration    : 0.5
  max_duration    : 15.0

# --- 3. MODEL ARCHITECTURE (Pure CTC Core) ---
model:
  backbone                 : "microsoft/wavlm-base-plus"       # Ringan, cocok untuk eksperimen awal
  # backbone               : "microsoft/wavlm-large"           # Akurasi tinggi, butuh VRAM besar
  # backbone               : "facebook/wav2vec2-large-xlsr-53" # Sangat bagus untuk fonem IPA
  # backbone               : "facebook/hubert-large-ls960-ft"  # Sangat stabil

  freeze_feature_extractor : True    
  
  mask_time_prob           : 0.05
  mask_time_length         : 10
  mask_feature_prob        : 0.05
  mask_feature_length      : 10

# --- 4. TRAINING HYPERPARAMETERS ---
train:
  epochs       : 20
  learning_rate: 1e-4     
  optimizer    : "adamw"  
  weight_decay : 0.005    
  use_8bit_adam: False # Set True jika library bitsandbytes sudah terinstall
  
  # [WAJIB] Karena model kita Murni CTC, bobotnya harus 100% (1.0)
  ctc_weight   : 1.0

  fp16: True
  
  # Real Batch Size = batch_size (8) * accum_steps (4) = 32
  gradient_accumulation_steps: 4
  
  device       : "cuda"
  logging_steps : 100